### ISSUE TITLE
docker-compose up error: No module named 'k_diffusion'

### ISSUE THREAD

**Issue by lukebelbina** [hlky/stable-diffusion#45] opened 2022-08-27 20:23 UTC
Ran `docker-compose up` and getting an error `ModuleNotFoundError: No module named 'k_diffusion'. Full output here:

```sh
$ docker-compose up
[+] Running 1/0
 ⠿ Container sd  Created                                                                                                                         0.0s
Attaching to sd
sd  | Validating model files...
sd  | checking model.ckpt...
sd  | model.ckpt is valid!
sd  | 
sd  | checking GFPGANv1.3.pth...
sd  | GFPGANv1.3.pth is valid!
sd  | 
sd  | checking RealESRGAN_x4plus.pth...
sd  | RealESRGAN_x4plus.pth is valid!
sd  | 
sd  | checking RealESRGAN_x4plus_anime_6B.pth...
sd  | RealESRGAN_x4plus_anime_6B.pth is valid!
sd  | 
sd  | Relauncher: Launching...
sd  | Traceback (most recent call last):
sd  |   File "scripts/webui.py", line 36, in <module>
sd  |     import k_diffusion as K
sd  | ModuleNotFoundError: No module named 'k_diffusion'
sd  | Relauncher: Process is ending. Relaunching in 0.5s...
sd  | Relauncher: Launching...
sd  |   Relaunch count: 1
sd  | Traceback (most recent call last):
sd  |   File "scripts/webui.py", line 36, in <module>
sd  |     import k_diffusion as K
sd  | ModuleNotFoundError: No module named 'k_diffusion'
sd  | Relauncher: Process is ending. Relaunching in 0.5s...
```

**Comment by hlky** [comment] 2022-08-27 21:09
Docker enviroment was not made by me, contributor @oc013 provided this, I can take a quick look to see if I can spot what's wrong though

**Comment by hlky** [comment] 2022-08-27 21:11
Is there a 'src' folder with several other folders inside of it?

I think maybe [this line](https://github.com/hlky/stable-diffusion/blob/1c123b50a35f080579d26aeed590a9444efd4e2e/Dockerfile#L25) is cleaning those folders, it's not a step that's used in the normal setup

**Comment by lukebelbina** [comment] 2022-08-27 21:34
> Is there a 'src' folder with several other folders inside of it?
> 
> I think maybe [this line](https://github.com/hlky/stable-diffusion/blob/1c123b50a35f080579d26aeed590a9444efd4e2e/Dockerfile#L25) is cleaning those folders, it's not a step that's used in the normal setup

here are the contents of src in the container:

```
(ldm) root@33074642d96d:/src# ls
 Dockerfile                          assets               environment.yaml   notebook_helpers.py   setup.py
 LICENSE                             configs              ldm                optimizedSD           src
'Launch Waifu Diffusion.lnk'         data                 ldm.cmd            outputs               txt2img.yaml
 README.md                           docker-compose.yml   main.py            run.cmd               webui.cmd
 Stable_Diffusion_v1_Model_Card.md   entrypoint.sh        models             scripts               webuildm.cmd
```

**Comment by hlky** [comment] 2022-08-27 22:14
contents of src\src I should say then
this might also be an issue whereby the docker file is calling it's own main folder src which would usually be called stable-diffusion, and there's the other src folder

then, depending on which directory is the working directory when the script is launched, this might cause an issue as well

but I think its that clean line, waiting to see contents of src\src

**Comment by lukebelbina** [comment] 2022-08-27 23:10
Here's the contens or src/src

```
(ldm) root@33074642d96d:/src/src# ls
gfpgan  realesrgan
```

**Comment by lukebelbina** [comment] 2022-08-27 23:18
I went and tried a rebuild with the `conda clean --all && \` line removed and same issue

**Comment by hlky** [comment] 2022-08-27 23:18
so the src/src folder still only has gfgpan and realesrgan?

**Comment by hlky** [comment] 2022-08-27 23:24
Ok i've changed the docker files to use /sd/ as the root directory equivalent to stable-diffusion for the regular setup
See if that works, it could be some sort of conflict with there being two directories named src

**Comment by oc013** [comment] 2022-08-28 01:10
Please the output of the build when it's failing. Your full output was only launching the container, not from building the image where it would have failed.

PS I would suggest reverting the changes, the files being in /src is not the issue.

**Comment by oc013** [comment] 2022-08-28 01:23
Please show the output of the build when it's failing. Your output was only launching the container, not from building the image where it would have failed.

You could run these commands to get a mostly fresh build:
```
docker-compose down
docker-compose build --no-cache --progress=plain
```
Show the output from here where it's failing to install the missing dependencies. Also please provide output of :
```
docker version
docker-compose -v
```
PS I would suggest reverting the changes, the files being in /src should not be an issue. conda clean --all just cleans up cache files to make the docker image smaller.
```
-a, --all
    Remove index cache, lock files, unused cache packages, and tarballs.
```

**Comment by oc013** [comment] 2022-08-28 01:43
I'll test with everything moved to `/sd`...

**Comment by oc013** [comment] 2022-08-28 02:25
I see the same error now after pulling all the changes, working on it.

```
sd  | Traceback (most recent call last):
sd  |   File "scripts/webui.py", line 39, in <module>
sd  |     import k_diffusion as K
sd  | ModuleNotFoundError: No module named 'k_diffusion'
sd  | Relauncher: Process is ending. Relaunching in 0.5s...
sd  | Relauncher: Launching...
```

**Comment by hlky** [comment] 2022-08-28 04:06
Thanks @oc013 

From what I saw the k-diffusion directory doesn't exist and there should be another one as well, they are both installed from the environment.yaml, or should be,  so I think they are probably getting deleted for some reason

**Comment by oc013** [comment] 2022-08-28 04:23
@hlky I think I know what the problem is, I probably need to move the initial setup for the conda env into the entrypoint script as well.  The volume that saves the conda env is possibly overwriting the initial setup. Give me a bit I'll work it out.

**Comment by hlky** [comment] 2022-08-28 04:50
Have you got it pulling changes when the container starts or anything like that? git pull of this repo will pull the stable version, you could probably add an option to switch to dev, check .github/sync.yml  on stable-diffusion-webui to see which files are synced are their destinations in this repo
There was a change to the webui.cmd that updates the environment from the environment.yaml file if there are any changes, if there are no changes it doesn't do anything, it's safe to run  both the conda env create command  and the update command without affecting the environment, they only properly run if either the environment doesn't exist, or the environment.yaml differs to the environment's current setup.
Just wanted to check you knew about that so could implement it if needed

**Comment by oc013** [comment] 2022-08-28 06:36
Once I deleted all the caching I had built in, I realized the issue.  I believe this issue should be resolved once the above is merged, my apologies.

@lukebelbina you can run the ./docker-reset.sh file I added or run the individual commands inside of it to fully clear things up and reclaim some diskspace, then docker-compose up and let me know how it goes

@hlky I did see that, just was trying to reduce the start up time so I added a small bit of code to only run those commands if the conda env doesn't exist or if the date modified timestamp on the environment.yaml changes

**Comment by hlky** [comment] 2022-08-28 13:54
#59

**Closed** 2022-08-28 14:33 UTC

**Comment by lukebelbina** [comment] 2022-08-28 17:31
@oc013 and @hlky - thank you both so much for fixing this and your work, confirmed it is now working this morning!

**Comment by mohammedalsayegh** [comment] 2022-08-29 14:31
After running ``docker-compose up`` I get the fallowing ModuleNotFoundError but with frontend instead of  'k_diffusion'

```
Traceback (most recent call last):
sd  |   File "/sd/scripts/webui.py", line 3, in <module>
sd  |     from frontend.frontend import draw_gradio_ui
sd  | ModuleNotFoundError: No module named 'frontend'
sd  | entrypoint.sh: Process is ending. Relaunching in 0.5s...
sd  | entrypoint.sh: Launching...'
sd  | Relaunch count: 135
```
Running ``./docker-reset.sh`` or reclone with new image result with same error

**Comment by oc013** [comment] 2022-08-29 14:41
@mohammedalsayegh this is not a docker problem, the code is wrong as far as I can tell

**Comment by hlky** [comment] 2022-08-29 14:48
it's an issue with the Dockerfile not pulling the changes from the repo properly

the ui was refactored and changes need to be pulled from the main repo

**Comment by oc013** [comment] 2022-08-29 15:04
The Dockerfile does not pull the code, it is up to the user to git pull updates from the repo and restart the container which will use the code via a mounted volume. I detailed everything here #93 for future reference should you need to update but it should be a minimal maintenance system other than possibly adding new model files that need to be pre-downloaded.

Working on another project now, but I recloned this repo and ran everything from fresh per the instructions and it works with no problem, my mistake it's the user.

I see now he did not update the code from the repo because it still has that stray single quote in the one message in the console.  It's not relevant to this issue he commented on.

**Comment by mohammedalsayegh** [comment] 2022-08-29 16:14
> @mohammedalsayegh this is not a docker problem, the code is wrong as far as I can tell

Both ``webui.cmd`` and ``webuildm.cmd`` worked with no issue under a conda-built environment, so I thought it was likely a missing something in the Dockerfile.

**Comment by mohammedalsayegh** [comment] 2022-08-29 16:43
It works from ``/home/user_name/`` directory in WSL but get the above path error when repository clone placed in ``/mnt/c/..etc``

**Comment by oc013** [comment] 2022-08-29 17:18
@mohammedalsayegh I'm not sure what `/mnt/c/..etc` is, maybe it's a windows thing 

Run this and send the output
```
docker exec -it sd bash
pwd
```

**Comment by mohammedalsayegh** [comment] 2022-08-29 18:15
> @mohammedalsayegh I'm not sure what `/mnt/c/..etc` is, maybe it's a windows thing
> 


In my context, I was referring to any subdirectory of C under WSL with ``/mnt/c/..etc``. Which it turn out not the case. As soon as Docker and WSL are rebooted, it works.

In spite of deleting the docker volume and image, changing the directory, and cloning again, I have not been able to reproduce the same error. There may have been a problem with WSL accessing Windows directory permissions at runtime.

There was a second error during docker compose up, but it was resolved after multiple attempts of ``sudo docker compose up``.


```
[+] Building 4.8s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                   0.1s
 => => transferring dockerfile: 731B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04                                                                4.7s
------
 > [internal] load metadata for docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/nvidia/cuda/manifests/11.3.1-runtime-ubuntu20.04": EOF
```

The sd allocated correctly on second run
```
(base) PS C:\Users\red> docker exec -it sd bash
(ldm) root@25ee48096a4e:/sd# pwd
/sd
```
